title: Karthik Sridhar
description: 'Second Year Computer Science student at the University of Bristol'
author: 'Karthik Sridhar'

theme: jekyll-theme-startbootstrap-agency

sass:
  style: compressed

assets_path: 'https://kartsridhar.github.io/assets/'

collections:
  projects:
