brand:
  name: Karthik Sridhar
menu-string: ''

nav:
  - title: Profile
    url: '#services'
  - title: Projects
    url: '#portfolio'
  - title: Career
    url: '#about'
  - title: Contact
    url: '#contact'

copyright: Copyright &copy; Karthik 2019

social-buttons:
  - icon: fa fa-twitter
    url: 'https://twitter.com/kartsridhar'
  - icon: fa fa-facebook
    url: 'https://facebook.com/theblakfyre'
  - icon: fa fa-linkedin
    url: 'https://www.linkedin.com/in/karthik-sridhar-343546147/'

modal:
  date-string: 'Date: '
  client-string: 'Client: '
  category-string: 'Category: '
  close-icon: 'fa fa-times'
  close-string: 'Close Project'
